# Generated by Django 3.2.16 on 2023-10-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0002_rename_employee_funcionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='codigo',
            field=models.IntegerField(max_length=20),
        ),
    ]
