# Generated by Django 3.2.16 on 2023-10-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0003_alter_funcionario_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='codigo',
            field=models.IntegerField(),
        ),
    ]
